# Servidor
server.port=9091

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/diariopay

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Sesión
server.servlet.session.timeout=2h

# Logs
logging.level.com.diariopay=DEBUG
