server.port=${PORT:9090}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/diariopay}

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.session.timeout=2h

logging.level.com.diariopay=DEBUG


twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.from=${TWILIO_FROM}