server.port=${PORT:9090}

# Zona horaria de Colombia para toda la app (fechas, horas, cron del scheduler)
spring.jackson.time-zone=America/Bogota

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/diariopay}

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.session.timeout=2h

logging.level.com.diariopay=DEBUG


twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp.from=${TWILIO_WHATSAPP_FROm}


# Cookies seguras (solo HTTPS en producci?n)
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# Cambia a true cuando tengas HTTPS

# Cabeceras de seguridad HTTP
server.servlet.session.cookie.same-site=lax
