server.port=${PORT:9090}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/diariopay}

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.session.timeout=2h

logging.level.com.diariopay=DEBUG


twilio.account.sid=AC2744f91ac5dbbae0d1caa94fb1e94782
twilio.auth.token=2384ec969ddeccf4fda807045ae25e0a
twilio.whatsapp.from=whatsapp:+14155238886


# Cookies seguras (solo HTTPS en producci�n)
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
# Cambia a true cuando tengas HTTPS

# Cabeceras de seguridad HTTP
server.servlet.session.cookie.same-site=strict